services:
  marauder-builder:
    image: esp32marauder-builder-marauder-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ESP32_VERSION: ${ESP32_VERSION}
        ESP32_CHIP: ${ESP32_CHIP}
        MARAUDER_BOARD: ${MARAUDER_BOARD}
        IS_CUSTOM_AUTO: ${IS_CUSTOM_AUTO}
    container_name: esp32marauder_builder
    environment:
      - ESP32_VERSION=${ESP32_VERSION}
      - ESP32_CHIP=${ESP32_CHIP}
      - MARAUDER_BOARD=${MARAUDER_BOARD}
      - IS_CUSTOM_AUTO=${IS_CUSTOM_AUTO}
      - FQBN=${FQBN}
    volumes:
      - ./output:/project/output
      - ./platform.txt:/project/platform.txt
      - ./run.sh:/project/run.sh
      - ./custom_boards:/project/custom_boards:ro
    working_dir: /project
    entrypoint: /bin/bash
    command: ./run.sh
    restart: "no"
