services:
  marauder-builder:
    build:
      context: .
      args:
        ESP32_VERSION: ${ESP32_VERSION}
        ESP32_CHIP: ${ESP32_CHIP}
        MARAUDER_BOARD: ${MARAUDER_BOARD}
    container_name: esp32marauder_builder
    environment:
      - ESP32_VERSION=${ESP32_VERSION}
      - ESP32_CHIP=${ESP32_CHIP}
      - MARAUDER_BOARD=${MARAUDER_BOARD}
    volumes:
      - ./output:/project/output
      - ./platform.txt:/project/platform.txt
      - ./run.sh:/project/run.sh
    working_dir: /project
    entrypoint: /bin/bash
    command: ./run.sh
